sudo: required
language: swift
osx_image: xcode9
before_install:
  - wget https://download.docker.com/mac/stable/DockerToolbox.pkg
  - sudo installer -verbose -pkg DockerToolbox.pkg -target /
  # - wget https://s3.amazonaws.com/joelsaltzman.com/Docker.tar
  # - tar -xvf Docker.tar
  # - sudo xattr -d -r com.apple.quarantine Docker.app
  # - open Docker.app
  #! -f /usr/local/bin/docker
  - LIMIT=1; while [ $LIMIT -lt 10 ]; do sleep 2; echo "waiting on file ($LIMIT)"; ((LIMIT++)); done; ls -l /usr/local/bin/docker
  - open /Applications/Docker.app
  - LIMIT=1; while [ $LIMIT -lt 10 ]; do sleep 2; echo "waiting on file ($LIMIT)"; ((LIMIT++)); done; docker ps
  # - sleep 5
  # - docker ps
script:
  - "docker ps"
  - "swift test"
