sudo: required
language: swift
osx_image: xcode9
before_install:
  - brew update
  - brew install docker
  - brew services start docker
  - eval "$(docker-machine env default)"
  - docker --version
script:
  - "which docker"
  - "docker ps"
  - "swift test"
