language: swift
osx_image: xcode9
sudo: required
services:
  - docker
# before_install:
# - brew update
# - brew install Caskroom/cask/virtualbox docker docker-machine
# - brew services start docker-machine
# - docker-machine create --driver virtualbox default
- eval "$(docker-machine env default)"
- docker --version
script:
  - "swift test"
