sudo: required
language: swift
osx_image: xcode9
before_install:
  - mkdir ~/Applications
  - wget https://s3.amazonaws.com/joelsaltzman.com/Docker.tar
  - tar -xf Docker.tar
  - sudo xattr -d -r com.apple.quarantine Docker.app
  - mv Docker.app ~/Applications/Docker.app
  - open ~/Applications/Docker.app
  - LIMIT=1; while [ $LIMIT -lt 20 ]; do sleep 2; echo "waiting on file ($LIMIT)"; ((LIMIT++)); done;
  - ls -al /usr/local/bin/d*
  - wget https://download.docker.com/mac/stable/DockerToolbox.pkg
  - sudo installer -verboseR -pkg DockerToolbox.pkg -target /
  - LIMIT=1; while [ $LIMIT -lt 20 ]; do sleep 2; echo "waiting on file ($LIMIT)"; ((LIMIT++)); done
  - ls -al /Applications/
  - open "/Applications/Docker/Docker Quickstart Terminal"
  - LIMIT=1; while [ $LIMIT -lt 20 ]; do sleep 2; echo "waiting on file ($LIMIT)"; ((LIMIT++)); done
  - ls -al /usr/local/bin/d*
script:
  - "docker ps"
  - "swift test"
